services:
  # BACKEND
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start
  # DATABASE
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vibe_view
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  # ADMINER
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
